# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anna', '0002_auto_20160318_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
